brew "nvim"
brew "tmux"

# Tooling
brew "lazygit"
brew "jq"

# Kubernetes
brew "k9s"
brew "kubectl"

###########################
#  Programming languages  #
###########################

# GO
brew "golang"
brew "gopls"

# JavaScript/TypeScript
brew "nodejs"
brew "npm"
brew "pnpm"
brew "typescript"
brew "typescript-language-server"