#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/github.com ~/dev -mindepth 1 -type d -exec test -e '{}/.git' ';' -print -prune | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

sudo docker run --network host -it --rm \
	-e PUID=$(id -u) -e PGID=$(id -g) \
	-w /home/dev/$selected_name \
	-v $selected:/home/dev/$selected_name \
	-v ~/.ssh:/home/dev/.ssh \
	-v ~/.gitconfig:/home/dev/.gitconfig \
	--env DISPLAY=$DISPLAY \
	--env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
	--volume /tmp/.X11-unix:/tmp/.X11-unix \
	--volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
	devbox-$(id -u)-$(id -g):latest /scripts/entrypoint.sh
