#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/github.com ~/dev -mindepth 1 -type d -exec test -e '{}/.git' ';' -print -prune | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

echo $selected
echo $selected_name
sudo docker run --network host -it -v $selected:/dev_env/$selected_name -w /dev_env/$selected_name -v ~/.ssh:/home/dev/.ssh -v ~/.ssh:/home/ubuntu/.ssh -v ~/.gitconfig:/home/dev/.gitconfig -v ~/.gitconfig:/home/ubuntu/.gitconfig --rm -e PUID=$(id -u) -e PGID=$(id -g) --name dc ghcr.io/s1monb/dev:latest /scripts/entrypoint.sh
