#!/usr/bin/env bash

mkdir ~/compile-it
mkdir ~/compile-it/.config
mkdir ~/compile-it/.local

# Copy files
echo "copying ~/.local folders"
cd ~/.local
find . -depth -maxdepth 2 -type d | grep -e "nvim" -e "scripts" -e "fish" -e "tmux" -e "lazygit" | xargs -I '{}' cp -r '{}' ~/compile-it/.local

echo "copying ~/.config folders"
cd ~/.config
find . -depth -maxdepth 2 -type d | grep -e "nvim" -e "fish" -e "tmux" -e "lazygit" | xargs -I '{}' cp -r '{}' ~/compile-it/.config

cd ~/

# Compress and tarball it
echo "compressing..."
tar -cz -f compiled.tar.gz ~/compile-it


rm -rf ~/compile-it

echo "done"
