version: "3"

tasks:
  install-locally:
    desc: Install everything on the local machine within .config-folder
    cmds:
      - rm -rf ~/.config/tmux ~/.config/nvim ~/.config/fish ~/.config/lazygit ~/.config/bin
      - cp -r ./env/.config/tmux ~/.config/tmux
      - cp -r ./env/.config/nvim ~/.config/nvim
      - cp -r ./env/.config/fish ~/.config/fish
      - cp -r ./env/.config/lazygit ~/.config/lazygit
      - cp -r ./env/.config/bin ~/.config/bin

  clear-local-cache:
    desc: Clear the local config cache
    cmds:
      - rm -rf ~/.local/share/nvim 
      - rm -rf ~/.local/state/nvim

  pack:
    desc: Pack the cache, cfg-files and dev-script into one gzip
    cmds:
      - mkdir -p ./backup
      - mkdir -p ./backup/{share,state}/{nvim}
      - cp -r ~/.local/state/nvim     ./backup/state/nvim
      - cp -r ~/.local/share/nvim     ./backup/share/nvim
      - cp -r env                     ./backup/
      - cp Taskfile.yaml              ./backup/
      - tar -czvf backup.tar.gz       ./backup
      - rm -rf ./backup

  unpack:
    desc: Unpack the cache and cfg-files from the zipped tar-archive
    cmds:
      - task install-locally
      - task clear-local-cache
      - cp -r ./state/nvim ~/.local/state/
      - cp -r ./share/nvim ~/.local/share/
