brew "nvim"
brew "tmux"

# Tooling
brew "luarocks"
brew "lazygit"
brew "jq"
brew "direnv"
brew "nushell"

# Kubernetes
brew "k9s"
brew "kubectl"

###########################
#  Programming languages  #
###########################

# GO
brew "golang"
brew "gopls"
tap "silenceper/tap"
brew "gowatch"
brew "delve"

# JavaScript/TypeScript
brew "nodejs"
brew "npm"
brew "pnpm"
brew "typescript"
brew "typescript-language-server"
brew "python3"
