brew "nvim"
brew "tmux"

# Tooling
brew "luarocks"
brew "lazygit"
brew "jq"
brew "direnv"
brew "nushell"
brew "go-task"
brew "terragrunt"

# Kubernetes
brew "k9s"
brew "kubectl"
brew "talosctl"
brew "helm"
brew "cilium-cli"

###########################
#  Programming languages  #
###########################

# GO
brew "golang"
brew "gopls"
tap "silenceper/tap"
brew "gowatch"
brew "delve"

# JavaScript/TypeScript
brew "nodejs"
brew "npm"
brew "pnpm"
brew "typescript"
brew "typescript-language-server"
brew "python3"

# Lua
brew "lua-language-server"
