name: Build Neovim Docker Image
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  XDG_CONFIG_HOME: /home/runner/.dotfiles

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Neovim
      run: |
        curl -Lo nvim.tar.gz https://github.com/neovim/neovim-releases/releases/download/v0.10.1/nvim-linux64.tar.gz
        tar xzf nvim.tar.gz
        mv nvim-linux64 ~/.nvim
        mkdir -p ~/.local/bin
        ln -s ~/.nvim/bin/nvim ~/.local/bin/nvim
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cp -r ./dotfiles ~/.dotfiles

    - name: Is Neovim installed?
      run: |
        ls -R ~/.dotfiles
    
    - name: Initialize lazy.nvim
      run: |
        nvim --headless -u ~/.dotfiles/nvim/init.lua "+qa"


    - name: Copy config and plugin data to Docker context
      run: |
        mkdir -p .nvim-data/share
        mkdir -p .nvim-data/state
        cp -r ~/.local/share/nvim .nvim-data/share
        cp -r ~/.local/state/nvim .nvim-data/state

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/nvim-dev:latest .
  
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/nvim-dev:latest