name: Build Neovim Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  XDG_CONFIG_HOME: /home/runner/.dotfiles

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create image
      run: |
        make create-final 
    - name: Tag image
      run: |
        docker image tag dc:latest ghcr.io/${{ github.repository_owner }}/dev:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image

      run: docker push ghcr.io/${{ github.repository_owner }}/dev:latest
